include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Management.gitlab-ci.yml

image: node:10.16.0

stages:
  - test
  - deploy

build:
  stage: test
  script:
    - npm install
    - npm run test
    - npm run test:coverage
  tags:
    - docker

deployToDev:
  stage: deploy
  script:
    - bash deploy/deployToDev.sh
  only:
    - develop

deployToStaging:
  stage: deploy
  script:
    - bash deploy/deployToStaging.sh
  when: manual
