export default {
  APP_LOGIN: 'APP_LOGIN',
  ACCOUNT_LOGOUT: 'ACCOUNT_LOGOUT',
  ACCOUNT_SET_IS_LOGGED_IN: 'ACCOUNT_SET_IS_LOGGED_IN',
  ACCOUNT_SET_ACCOUNT: 'ACCOUNT_SET_ACCOUNT',
  ACCOUNT_SET_PASSWORD: 'ACCOUNT_SET_PASSWORD',
  ACCOUNT_LOGIN_SET_ERROR: 'ACCOUNT_SET_ERROR',
  MODAL_TOGGLE: 'MODAL_TOGGLE',
  MODAL_SET_TYPE: 'MODAL_SET_TYPE'
};