export default {
  APP_LOGIN: 'APP_LOGIN',
  APP_ADD_LOADING_STATUS: 'APP_ADD_LOADING_STATUS',
  APP_REMOVE_LOADING_STATUS: 'APP_REMOVE_LOADING_STATUS',
  APP_RESET_LOADING_STATUS: 'APP_RESET_LOADING_STATUS',

  ACCOUNT_LOGOUT: 'ACCOUNT_LOGOUT',
  ACCOUNT_SET_IS_LOGGED_IN: 'ACCOUNT_SET_IS_LOGGED_IN',
  ACCOUNT_SET_ACCOUNT: 'ACCOUNT_SET_ACCOUNT',
  ACCOUNT_SET_PASSWORD: 'ACCOUNT_SET_PASSWORD',
  ACCOUNT_LOGIN_SET_ERROR: 'ACCOUNT_SET_ERROR',

  MODAL_TOGGLE: 'MODAL_TOGGLE',
  MODAL_SET_TYPE: 'MODAL_SET_TYPE',

  STREAMS_ADD_STREAM: 'STREAMS_ADD_STREAM',
  STREAMS_ADD_ERROR: 'STREAMS_ADD_ERROR'
};