export default {
  FORGOT: 'FORGOT',
  LOGIN: 'LOGIN',
  SIGN_UP: 'SIGN_UP',
  REPORT_USER: 'REPORT_USER',
  DONATE: 'DONATE',
  BAN: 'BAN',
  LINK_ACCOUNT: 'LINK_ACCOUNT',
  PEERPLAYS_LOGIN: 'PEERPLAYS_LOGIN'
};
